[fix] improve link readability
sqlalchemyorg/zzzeeksphinx pull request #15
Opened 2023-04-08 13:01 UTC by drc0

the link color contrast is not enough to be distinguished
improve the readability with underlined links for the docs main body content

2023-04-08 13:38 UTC, zzzeek requested changes
Hi -

I would much rather fix anything else before adding fixed underlines.

The docs that we generally emulate are MySQLs, example at https://dev.mysql.com/doc/refman/8.0/en/json.html 

So I didn't know how to quantitatively define "link color contrast is not enough to be distinguished", but here's a checker that looks like a lot of work and experience went into it, and it shows that **you are correct**!    https://webaim.org/resources/linkcontrastchecker/?fcolor=212529&bcolor=FFFFFF&lcolor=990000

here is what passes:

https://webaim.org/resources/linkcontrastchecker/?fcolor=212529&bcolor=FFFFFF&lcolor=E00000

please change the link color to E00000.   thanks !

cc @CaselIT

2023-04-08 13:50 UTC, CaselIT commented
Not sure I would trust that tool too much. This gets a pass, but it's basically invisible https://webaim.org/resources/linkcontrastchecker/?fcolor=212529&bcolor=FFFFFF&lcolor=757575
![image](https://user-images.githubusercontent.com/16175304/230724729-45a0e853-96f3-4ca0-97e4-ac403e82c362.png)


regardless that red looks a but much, but I'm no designer, so it's fine by me

2023-04-08 13:54 UTC, drc0 commented
ok thanks for the feedback! I had to admin I'm (almost) red green color blind so slim red text with surrounding green accents are a lot confusing to me, but I have to admin #E00000 is at least an improvement from what is now, should we confirm that color?

2023-04-08 14:27 UTC, zzzeek commented
> ok thanks for the feedback! I had to admin I'm (almost) red green color blind so slim red text with surrounding green accents are a lot confusing to me, but I have to admin #E00000 is at least an improvement from what is now, should we confirm that color?

OK well is it enough?   I used the tool's recommendations assuming they come from some place of authority , we can also change the font spacing which might be a little tight

2023-04-08 14:29 UTC, zzzeek commented
-

> Not sure I would trust that tool too much. This gets a pass, but it's basically invisible https://webaim.org/resources/linkcontrastchecker/?fcolor=212529&bcolor=FFFFFF&lcolor=757575 ![image](https://user-images.githubusercontent.com/16175304/230724729-45a0e853-96f3-4ca0-97e4-ac403e82c362.png)
> 
> regardless that red looks a but much, but I'm no designer, so it's fine by me

dunno this is w3 stuff, comes straight from the top   https://www.w3.org/TR/WCAG20/

2023-04-08 14:30 UTC, zzzeek commented
i would gather there's a tool that would just look at our whole site and find issues

of course, "we're only in English" is one of our biggest issues....

2023-04-08 14:49 UTC, CaselIT commented
> of course, "we're only in English" is one of our biggest issues....

Well gpts should help a lot here, since they seem quite good at translating text

2023-04-14 11:29 UTC, drc0 commented
superseded by #17

2023-04-14 11:29 UTC, closed without merging